import { CGProject } from './types';

export const defaultProject: CGProject = {
  id: 'proj_default_broadcast',
  name: 'Makasna Broadcast Package',
  version: '1.0.0',
  canvas: {
    width: 1920,
    height: 1080,
    fps: 60,
  },
  datasets: [
    {
      id: 'ds_leaderboard',
      name: 'Klasemen Balap / Pertandingan',
      sourceType: 'manual',
      headers: ['Posisi', 'Nama', 'Klub/Tim', 'Waktu/Poin'],
      rows: [
        { Posisi: '1', Nama: 'Bambang Pamungkas', 'Klub/Tim': 'Garuda FC', 'Waktu/Poin': '1:24.450' },
        { Posisi: '2', Nama: 'Reza Rahadian', 'Klub/Tim': 'Speed Hunters', 'Waktu/Poin': '+0.124' },
        { Posisi: '3', Nama: 'Nicholas Saputra', 'Klub/Tim': 'Apex Racing', 'Waktu/Poin': '+0.380' },
        { Posisi: '4', Nama: 'Iqbaal Ramadhan', 'Klub/Tim': 'Redline Team', 'Waktu/Poin': '+0.720' },
        { Posisi: '5', Nama: 'Chicco Jerikho', 'Klub/Tim': 'Turbo Velocity', 'Waktu/Poin': '+1.105' },
      ],
      lastUpdated: Date.now(),
    },
    {
      id: 'ds_rundown_guests',
      name: 'Daftar Narasumber Live',
      sourceType: 'manual',
      headers: ['Nama', 'Jabatan', 'Topik'],
      rows: [
        { Nama: 'Dr. Ir. Rengga Pratama, M.Kom', Jabatan: 'Pakar Penyiaran Digital & AI', Topik: 'Masa Depan Broadcast CG' },
        { Nama: 'Siti Rahmawati, S.Sos', Jabatan: 'Direktur Produksi Televisi', Topik: 'Efisiensi Operasional Studio' },
      ],
      lastUpdated: Date.now(),
    },
  ],
  templates: [
    {
      id: 'tpl_lower_third_news',
      name: 'Lower Third News Modern',
      category: 'lower-third',
      defaultLayer: 'L2',
      duration: 5.0,
      markers: {
        intro: { start: 0, end: 0.8 },
        hold: { start: 0.8, end: 4.2, loop: true },
        outro: { start: 4.2, end: 5.0 },
      },
      layers: [
        {
          id: 'layer_accent_bar',
          name: 'Accent Pill / Tag Bar',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 120,
            y: 830,
            width: 140,
            height: 32,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#ff1744',
            borderRadius: 6,
            dropShadow: { x: 0, y: 4, blur: 12, color: 'rgba(255, 23, 68, 0.4)' },
          },
          content: {
            shapeType: 'pill',
          },
          keyframes: [
            { id: 'kf_bar_0', time: 0, props: { scaleX: 0, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_bar_1', time: 0.4, props: { scaleX: 1, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_bar_2', time: 4.2, props: { scaleX: 1, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_bar_3', time: 4.8, props: { scaleX: 0, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
        {
          id: 'layer_accent_tag_text',
          name: 'Category Tag Text',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 130,
            y: 836,
            width: 120,
            height: 20,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#ffffff',
            fontFamily: 'Inter',
            fontSize: 14,
            fontWeight: 800,
            letterSpacing: 1.5,
            textAlign: 'center',
          },
          content: {
            text: 'LIVE REPORT',
          },
          dataBinding: {
            column: 'Topik',
            fallback: 'LIVE REPORT',
          },
          keyframes: [
            { id: 'kf_tag_0', time: 0.1, props: { opacity: 0 }, easing: 'linear' },
            { id: 'kf_tag_1', time: 0.45, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_tag_2', time: 4.2, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_tag_3', time: 4.6, props: { opacity: 0 }, easing: 'linear' },
          ],
        },
        {
          id: 'layer_bg_plate',
          name: 'Main Background Plate',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 120,
            y: 870,
            width: 760,
            height: 90,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#0f172a',
            stroke: 'rgba(255, 255, 255, 0.15)',
            strokeWidth: 1.5,
            borderRadius: 12,
            dropShadow: { x: 0, y: 16, blur: 32, color: 'rgba(0, 0, 0, 0.65)' },
          },
          content: {
            shapeType: 'rect',
          },
          mask: {
            enabled: true,
            type: 'rect',
            x: 120,
            y: 870,
            width: 760,
            height: 90,
          },
          keyframes: [
            { id: 'kf_bg_0', time: 0, props: { x: -600, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_bg_1', time: 0.6, props: { x: 120, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_bg_2', time: 4.2, props: { x: 120, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_bg_3', time: 4.9, props: { x: -700, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
        {
          id: 'layer_guest_name',
          name: 'Narasumber Name (Headline)',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 150,
            y: 884,
            width: 700,
            height: 40,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#ffffff',
            fontFamily: 'Inter',
            fontSize: 28,
            fontWeight: 800,
            textAlign: 'left',
            autoShrink: true,
            dropShadow: { x: 0, y: 2, blur: 6, color: 'rgba(0, 0, 0, 0.5)' },
          },
          content: {
            text: 'Dr. Ir. Rengga Pratama, M.Kom',
          },
          dataBinding: {
            column: 'Nama',
            fallback: 'Dr. Ir. Rengga Pratama, M.Kom',
          },
          keyframes: [
            { id: 'kf_name_0', time: 0.2, props: { y: 920, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_name_1', time: 0.7, props: { y: 884, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_name_2', time: 4.2, props: { y: 884, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_name_3', time: 4.7, props: { y: 920, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
        {
          id: 'layer_guest_title',
          name: 'Narasumber Subtitle / Jabatan',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 150,
            y: 926,
            width: 700,
            height: 24,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#94a3b8',
            fontFamily: 'Inter',
            fontSize: 16,
            fontWeight: 500,
            textAlign: 'left',
            autoShrink: true,
          },
          content: {
            text: 'Pakar Penyiaran Digital & AI Developer',
          },
          dataBinding: {
            column: 'Jabatan',
            fallback: 'Pakar Penyiaran Digital & AI Developer',
          },
          keyframes: [
            { id: 'kf_title_0', time: 0.35, props: { y: 950, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_title_1', time: 0.8, props: { y: 926, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_title_2', time: 4.2, props: { y: 926, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_title_3', time: 4.6, props: { y: 950, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
      ],
    },
    {
      id: 'tpl_sports_leaderboard',
      name: 'Leaderboard Pintar (Repeater Engine)',
      category: 'leaderboard',
      defaultLayer: 'L1',
      duration: 10.0,
      markers: {
        intro: { start: 0, end: 1.2 },
        hold: { start: 1.2, end: 8.5, loop: false },
        outro: { start: 8.5, end: 10.0 },
      },
      repeater: {
        enabled: true,
        datasetId: 'ds_leaderboard',
        rowHeight: 64,
        maxRows: 6,
        staggerDelay: 0.08,
      },
      layers: [
        {
          id: 'layer_lb_header_bg',
          name: 'Header Banner',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 460,
            y: 200,
            width: 1000,
            height: 72,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#0284c7',
            borderRadius: 8,
            dropShadow: { x: 0, y: 10, blur: 24, color: 'rgba(0, 0, 0, 0.5)' },
          },
          content: { shapeType: 'rect' },
          keyframes: [
            { id: 'kf_hbg_0', time: 0, props: { y: 140, opacity: 0 }, easing: 'easeOutBack' },
            { id: 'kf_hbg_1', time: 0.5, props: { y: 200, opacity: 1 }, easing: 'easeOutBack' },
            { id: 'kf_hbg_2', time: 8.5, props: { y: 200, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_hbg_3', time: 9.3, props: { y: 140, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
        {
          id: 'layer_lb_title',
          name: 'Header Title Text',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 480,
            y: 218,
            width: 960,
            height: 36,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#ffffff',
            fontFamily: 'Inter',
            fontSize: 26,
            fontWeight: 900,
            letterSpacing: 2,
            textAlign: 'center',
          },
          content: { text: 'KLASEMEN SEMENTARA - RACE 1' },
          keyframes: [
            { id: 'kf_ht_0', time: 0.2, props: { opacity: 0 }, easing: 'linear' },
            { id: 'kf_ht_1', time: 0.6, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_ht_2', time: 8.5, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_ht_3', time: 9.0, props: { opacity: 0 }, easing: 'linear' },
          ],
        },
        {
          id: 'layer_repeater_row_bg',
          name: 'Row Item Plate [Repeater]',
          type: 'repeater-row',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 460,
            y: 282,
            width: 1000,
            height: 56,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: 'rgba(15, 23, 42, 0.95)',
            stroke: 'rgba(255, 255, 255, 0.1)',
            strokeWidth: 1,
            borderRadius: 6,
          },
          content: { shapeType: 'rect' },
          keyframes: [
            { id: 'kf_row_0', time: 0.3, props: { x: 360, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_row_1', time: 0.8, props: { x: 460, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_row_2', time: 8.5, props: { x: 460, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_row_3', time: 9.2, props: { x: 360, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
      ],
    },
    {
      id: 'tpl_scorebug_match',
      name: 'Scorebug & Live Match Clock',
      category: 'scorebug',
      defaultLayer: 'L3',
      duration: 60.0,
      markers: {
        intro: { start: 0, end: 0.6 },
        hold: { start: 0.6, end: 58.0, loop: true },
        outro: { start: 58.0, end: 60.0 },
      },
      layers: [
        {
          id: 'layer_sb_bg',
          name: 'Scorebug Container',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 120,
            y: 60,
            width: 480,
            height: 48,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#0f172a',
            stroke: 'rgba(255, 255, 255, 0.2)',
            strokeWidth: 1.5,
            borderRadius: 8,
            dropShadow: { x: 0, y: 8, blur: 20, color: 'rgba(0, 0, 0, 0.6)' },
          },
          content: { shapeType: 'rect' },
          keyframes: [
            { id: 'kf_sb_0', time: 0, props: { y: 10, opacity: 0 }, easing: 'easeOutCubic' },
            { id: 'kf_sb_1', time: 0.5, props: { y: 60, opacity: 1 }, easing: 'easeOutCubic' },
            { id: 'kf_sb_2', time: 58.0, props: { y: 60, opacity: 1 }, easing: 'easeInCubic' },
            { id: 'kf_sb_3', time: 59.5, props: { y: 10, opacity: 0 }, easing: 'easeInCubic' },
          ],
        },
        {
          id: 'layer_sb_teams',
          name: 'Home vs Away & Score',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 140,
            y: 72,
            width: 320,
            height: 24,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#ffffff',
            fontFamily: 'JetBrains Mono',
            fontSize: 18,
            fontWeight: 700,
            textAlign: 'left',
          },
          content: { text: 'IDN  2 - 1  MAS' },
          keyframes: [
            { id: 'kf_sbt_0', time: 0.2, props: { opacity: 0 }, easing: 'linear' },
            { id: 'kf_sbt_1', time: 0.6, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_sbt_2', time: 58.0, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_sbt_3', time: 59.5, props: { opacity: 0 }, easing: 'linear' },
          ],
        },
        {
          id: 'layer_sb_clock',
          name: 'Match Timer Badge',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          transform: {
            x: 470,
            y: 72,
            width: 110,
            height: 24,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            anchorX: 0,
            anchorY: 0,
          },
          style: {
            fill: '#00e676',
            fontFamily: 'JetBrains Mono',
            fontSize: 16,
            fontWeight: 800,
            textAlign: 'right',
          },
          content: { text: "78:24" },
          keyframes: [
            { id: 'kf_sbc_0', time: 0.3, props: { opacity: 0 }, easing: 'linear' },
            { id: 'kf_sbc_1', time: 0.6, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_sbc_2', time: 58.0, props: { opacity: 1 }, easing: 'linear' },
            { id: 'kf_sbc_3', time: 59.5, props: { opacity: 0 }, easing: 'linear' },
          ],
        },
      ],
    },
  ],
  rundown: [
    {
      id: 'item_1',
      title: 'Opening - Dr. Rengga Pratama',
      templateId: 'tpl_lower_third_news',
      targetLayer: 'L2',
      dataOverrides: {
        Nama: 'Dr. Ir. Rengga Pratama, M.Kom',
        Jabatan: 'Pakar Penyiaran Digital & AI Developer',
        Topik: 'LIVE EXCLUSIVE',
      },
      status: 'idle',
      autoOutro: false,
    },
    {
      id: 'item_2',
      title: 'Tamu 2 - Siti Rahmawati',
      templateId: 'tpl_lower_third_news',
      targetLayer: 'L2',
      dataOverrides: {
        Nama: 'Siti Rahmawati, S.Sos',
        Jabatan: 'Direktur Produksi Televisi Nasional',
        Topik: 'STUDIO LIVE',
      },
      status: 'idle',
      autoOutro: false,
    },
    {
      id: 'item_3',
      title: 'Klasemen Balapan Race 1',
      templateId: 'tpl_sports_leaderboard',
      targetLayer: 'L1',
      dataOverrides: {},
      status: 'idle',
      autoOutro: false,
    },
    {
      id: 'item_4',
      title: 'Scorebug Pertandingan',
      templateId: 'tpl_scorebug_match',
      targetLayer: 'L3',
      dataOverrides: {},
      status: 'idle',
      autoOutro: false,
    },
  ],
};
